modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name} for ${minecraft_version}"
displayURL="${mod_sources}" #optional
logoFile="icon.png" #optional
credits="Hendrix-Shen" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
MagicLib unofficial (Neo)Forge port.

${mod_description}
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"